### ISSUE TITLE
Please explain about lists

### ISSUE THREAD

**Issue by pilhuhn** [manton/tweetmarker#1]
Can you please explain how lists are stored/retrieved?

**Comment by manton** [comment]
Sure, lists are stored using a collection name in the format "list.id", e.g. "list.123456" if that is the Twitter list ID.

**Comment by pilhuhn** [comment]
Is that list.id or lists.id (as written in https://github.com/manton/tweetmarker/blob/master/documentation/v2.md )

**Comment by manton** [comment]
Sorry, you're right. It's plural: lists.id. Thanks!
