### ISSUE TITLE
Version 2 documentation is incomplete

### ISSUE THREAD

**Issue by chockenberry** [manton/tweetmarker#3]
The documentation for getting the last read marker is incomplete:

https://github.com/manton/tweetmarker/blob/master/documentation/v2.md#get-last-read-marker

The collection includes as "username" key that contains the parameter passed in with the request. It will make me feel better about relying on this key/value if it's documented :-)

**Comment by manton** [comment]
You're right, the documentation was out of date. Username is a supported value and won't go away, so I've updated the documentation. Thanks!

(While there, I also updated the examples to show the Twitter ID as a quoted string. I didn't originally intend this, but by the time it was pointed out to me there were already shipped clients using v2, so now the documentation matches.)

**Comment by chockenberry** [comment]
I was just about to submit a bug about the ID being a string. Thanks for the preemptive update!
