### ISSUE TITLE
Options for using Tweet Marker for a single user with open source client

### ISSUE THREAD

**Issue by queuebit** [manton/tweetmarker#4]
I have been using / enjoying http://rainbowstream.org Twitter client recently, but it doesn't have Tweet Marker support.

Since it is an open source Python client (no real app developer who I would expect to pay for the Tweet Marker API), what are my options for getting an API key either for personal use or somehow bundled into the open source app?

Thanks.

**Comment by manton** [comment]
I'm not sure what the best solution is for open source apps, but getting an API key for personal use is no problem. If you don't mind, drop me an email at support@riverfold.com and I'll send you one.
